# Generated by Django 2.0.6 on 2018-06-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('file', models.FileField(upload_to='file/')),
                ('note', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NeuralNetwork_result',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.TextField()),
                ('iteration_times', models.IntegerField()),
                ('test_data_num', models.IntegerField()),
                ('RMSE', models.FloatField()),
                ('R_squared', models.FloatField()),
                ('data_file_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tensorflow_test_result',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.TextField()),
                ('iteration_times', models.IntegerField()),
                ('variable1', models.FloatField()),
                ('variable2', models.FloatField()),
                ('variable3', models.FloatField()),
                ('loss', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='worker_check_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostIP', models.TextField()),
                ('time_last_check', models.DateTimeField()),
                ('isBusy', models.BooleanField()),
            ],
        ),
    ]
